/**
 * SellX Semantic Service
 *
 * Uses embeddings generated by all-MiniLM-L6-v2
 * and cosine similarity to find similar products.
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

import { ProductModel } from "../models/ProductModel.js";


const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);


// product_embeddings.json is located at:
// server/data_storage/product_embeddings.json
const embeddingsPath = path.join(
  __dirname,
  "..",
  "..",
  "data_storage",
  "product_embeddings.json"
);


let embeddingData = null;


/**
 * Load product embeddings once and keep them in memory.
 */
function loadEmbeddings() {
  if (embeddingData) {
    return embeddingData;
  }

  if (!fs.existsSync(embeddingsPath)) {
    console.error(
      `Embedding file not found: ${embeddingsPath}`
    );

    return [];
  }

  try {
    const rawData = fs.readFileSync(
      embeddingsPath,
      "utf-8"
    );

    embeddingData = JSON.parse(rawData);

    console.log(
      `Loaded ${embeddingData.length} product embeddings.`
    );

    return embeddingData;

  } catch (error) {
    console.error(
      "Failed to load product embeddings:",
      error.message
    );

    return [];
  }
}


/**
 * Calculate cosine similarity between two vectors.
 *
 * Both vectors generated by all-MiniLM-L6-v2
 * contain 384 dimensions.
 */
function cosineSimilarity(vecA, vecB) {

  if (
    !Array.isArray(vecA) ||
    !Array.isArray(vecB) ||
    vecA.length !== vecB.length
  ) {
    return 0;
  }

  let dotProduct = 0;

  let normA = 0;

  let normB = 0;


  for (let i = 0; i < vecA.length; i++) {

    dotProduct += vecA[i] * vecB[i];

    normA += vecA[i] * vecA[i];

    normB += vecB[i] * vecB[i];
  }


  if (normA === 0 || normB === 0) {
    return 0;
  }


  return (
    dotProduct /
    (Math.sqrt(normA) * Math.sqrt(normB))
  );
}


/**
 * Find products similar to a given product.
 *
 * Uses the actual all-MiniLM-L6-v2 embeddings
 * generated by scripts/export_embeddings.py.
 */
function getSimilarProducts(productId, limit = 4) {

  const allProducts = ProductModel.findAll({});

  const targetProduct = ProductModel.findById(productId);


  if (!targetProduct) {
    return [];
  }


  const embeddings = loadEmbeddings();


  if (!embeddings.length) {
    console.warn(
      "No product embeddings available."
    );

    return [];
  }


  // Find embedding belonging to target product
  const targetEmbeddingRecord = embeddings.find(
    (item) =>
      String(item.productId) === String(productId)
  );


  if (
    !targetEmbeddingRecord ||
    !Array.isArray(targetEmbeddingRecord.embedding)
  ) {
    console.warn(
      `No embedding found for product ${productId}`
    );

    return [];
  }


  const targetVector =
    targetEmbeddingRecord.embedding;


  // Compare target against every other product
  const scored = allProducts
    .filter(
      (product) =>
        String(product.id) !== String(productId)
    )
    .map((product) => {

      const embeddingRecord = embeddings.find(
        (item) =>
          String(item.productId) === String(product.id)
      );


      if (
        !embeddingRecord ||
        !Array.isArray(embeddingRecord.embedding)
      ) {
        return null;
      }


      const similarity = cosineSimilarity(
        targetVector,
        embeddingRecord.embedding
      );


      const matchPercent = Math.min(
        99,
        Math.max(
          0,
          Math.round(similarity * 100)
        )
      );


      const priceDiff =
        Number(product.basePrice || 0) -
        Number(targetProduct.basePrice || 0);


      return {
        ...product,

        similarityScore:
          Math.round(similarity * 1000) / 1000,

        matchPercent,

        priceDiff,
      };
    })
    .filter(Boolean);


  // Highest semantic similarity first
  scored.sort(
    (a, b) =>
      b.similarityScore -
      a.similarityScore
  );


  return scored.slice(0, limit);
}


export const semanticService = {
  getSimilarProducts,
};